%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-rqt-plot
Version:        1.4.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rqt_plot package

License:        BSD
URL:            http://wiki.ros.org/rqt_plot
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       python%{python3_pkgversion}-catkin_pkg
Requires:       python%{python3_pkgversion}-matplotlib
Requires:       python%{python3_pkgversion}-numpy
Requires:       ros-jazzy-python-qt-binding >= 0.2.19
Requires:       ros-jazzy-qt-gui-py-common >= 0.2.25
Requires:       ros-jazzy-rclpy
Requires:       ros-jazzy-rosidl-runtime-py
Requires:       ros-jazzy-rqt-gui
Requires:       ros-jazzy-rqt-gui-py
Requires:       ros-jazzy-rqt-py-common
Requires:       ros-jazzy-std-msgs
Requires:       ros-jazzy-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-jazzy-ament-copyright
BuildRequires:  ros-jazzy-test-msgs
%endif

%description
rqt_plot provides a GUI plugin visualizing numeric values in a 2D plot using
different plotting backends.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/jazzy"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Wed Aug 06 2025 Brandon Ong <brandon@openrobotics.org> - 1.4.4-1
- Autogenerated by Bloom

* Mon May 12 2025 Brandon Ong <brandon@openrobotics.org> - 1.4.3-1
- Autogenerated by Bloom

* Thu Feb 13 2025 Brandon Ong <brandon@openrobotics.org> - 1.4.2-1
- Autogenerated by Bloom

* Tue Feb 11 2025 Brandon Ong <brandon@openrobotics.org> - 1.4.1-1
- Autogenerated by Bloom

* Fri Apr 19 2024 Brandon Ong <brandon@openrobotics.org> - 1.4.0-2
- Autogenerated by Bloom

* Thu Mar 28 2024 Brandon Ong <brandon@openrobotics.org> - 1.4.0-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Brandon Ong <brandon@openrobotics.org> - 1.3.2-2
- Autogenerated by Bloom

